### ISSUE TITLE
Nested Config

### ISSUE THREAD

**Issue by stevetayloruk** [fldsblzs/azure-csi-driver-sample#1]
The loading in of the secrets with ` builder.AddKeyPerFile("/mnt/secrets-store", true);` doesn't work with Keyvault due to the change in separator.

Keyvault doesn't allow the keys to use colon's (:) or underscore (_ or __) and are forced to use double hyphen (--).  When loading into configuration it doesn't populate.  

I've tried with flat config keys and it works fine.

Any solutions to this?

Thanks

**Comment by fldsblzs** [comment]
I had the same issue with the naming in Azure but was able to handle it using `objectAlias` in the `SecretProviderClass` [definition](https://github.com/fldsblzs/azure-csi-driver-sample/blob/main/deployments/helm/templates/secret-provider.yaml) for each secret.

In this sample the prefix TestApp was also used in the secret name to simulate a Key Vault with secrets for different services:
```        - |
          objectName: TestApp-Notification-MessagingPassword
          objectAlias: Notification:MessagingPassword
          objectType: secret
```

**Comment by stevetayloruk** [comment]
Works like a charm!  thank you.
